### ISSUE TITLE
Timeout vs Crash

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/sever#5]
Hi @JohnCoene do you know if shiny recognizes that the difference between an app "timing out" due to inactivity vs "crashing" because of poorly written R code? I am curious if it's possible to use sever to conditionally say:
> If the app crashed, tell user something went wrong. If inactive, tell the user we disconnected due to inactivity

**Comment by etiennebacher** [comment]
I would like to have this feature too. I think it must be possible to create a different message when the app is idle:
* [this article](https://shiny.rstudio.com/articles/js-events.html) makes the list of JS events in shiny and `idle` is one of them.
* [this SO answer](https://stackoverflow.com/questions/33839543/shiny-server-session-time-out-doesnt-work) shows how to close the app after a certain amount of time. Maybe it is possible to modify this function so that it displays an timeout message (which would be different from a crash message) after 15 minutes, which is the [default timeout value on shinyapps.io](https://docs.rstudio.com/shinyapps.io/applications.html#active-hours).

But as for many problems concerning JS or CSS, I personally don't know how to implement this :sweat_smile:

**Comment by JohnCoene** [comment]
@tyluRp sorry, I completely missed this issue.

I'm afraid shiny does not communicate the reason for the crash/timeout. All {sever} can do is listen for the `shiny:disconnected` event.

@etiennebacher This could be done, though I would create that as a separate function working independently from `sever`. Note that the events `idle` and `busy` simply indicate whether the server is computing things or not.

**Comment by etiennebacher** [comment]
> This could be done, though I would create that as a separate function working independently from `sever`

Thanks for your reactivity. Do you mean `sever` the function or the package? In other words, can we expect a feature like that to appear in this package or is it better to define a function outside of `sever}`?

**Comment by JohnCoene** [comment]
@etiennebacher I just pushed this new function: `rupture`.

```r
library(shiny)
devtools::load_all()

ui <- fluidPage(
 use_sever(),
 h1("rupture"),
 p("Wait for disconnected screen")
)

server <- function(input, output){
  # set ms to 5 seconds for test
 rupture(ms = 5000)
}

shinyApp(ui, server)
```

Note it's a whole new family of functions to work with `rupture` namely, while once disconnected one has to reload the entire page to trigger a reconnect (`sever`) with the idle screen there is no need, the session remains connected so only the `rupture` screen has to be removed, which is far more efficient.

**Comment by JohnCoene** [comment]
Feel free to reopen if this does not work.
